#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { spawnSync } = require('child_process');
let phase = 'manifest_preflight';
let verifiersStarted = 0;
function arg(name) { const exact = process.argv.indexOf(name); if (exact >= 0) return process.argv[exact + 1] || null; const prefix = name + '='; return process.argv.find((item) => item.startsWith(prefix))?.slice(prefix.length) || null; }
function candidate(root) { const explicit = arg('--candidate'); if (explicit) return path.resolve(explicit); const artifacts = path.join(root, 'artifacts'); const entries = fs.existsSync(artifacts) ? fs.readdirSync(artifacts).filter((item) => /^knowledge-v3\.3\.0-step1-rc4-r\d+\.zip$/i.test(item)) : []; if (entries.length !== 1) throw new Error('replay requires exactly one candidate in artifacts/ or --candidate'); return path.join(artifacts, entries[0]); }
function sha256(file) { return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }
function manifestPath(root, relative) { if (typeof relative !== 'string' || !relative || relative.includes('\\') || relative.startsWith('/') || relative.split('/').some((part) => !part || part === '.' || part === '..')) throw new Error('invalid replay manifest path: ' + String(relative)); const target = path.resolve(root, ...relative.split('/')); if (!target.startsWith(root + path.sep)) throw new Error('replay manifest path escapes root: ' + relative); return target; }
function verifyManifest(root) { const file = path.join(__dirname, 'manifest.json'); if (!fs.existsSync(file)) throw new Error('replay manifest is missing'); const manifest = JSON.parse(fs.readFileSync(file, 'utf8')); if (!Array.isArray(manifest.files) || manifest.files.length === 0) throw new Error('replay manifest has no files'); const seen = new Set(); for (const entry of manifest.files) { const relative = entry && entry.path; if (seen.has(relative)) throw new Error('duplicate replay manifest path: ' + relative); seen.add(relative); if (!entry || !/^[a-f0-9]{64}$/.test(entry.sha256 || '')) throw new Error('invalid replay manifest SHA-256: ' + relative); const target = manifestPath(__dirname, relative); let stat; try { stat = fs.lstatSync(target); } catch (_) { throw new Error('replay manifest file is missing: ' + relative); } if (!stat.isFile() || stat.isSymbolicLink()) throw new Error('replay manifest path is not a regular file: ' + relative); const actual = sha256(target); if (actual !== entry.sha256) { const error = new Error('replay manifest SHA-256 mismatch: ' + relative); error.manifest_path = relative; error.expected_sha256 = entry.sha256; error.actual_sha256 = actual; throw error; } } return { files: manifest.files.length }; }
function invoke(script, args, root) { verifiersStarted += 1; const child = spawnSync(process.execPath, [path.join(__dirname, 'tools', script), ...args], { cwd: path.dirname(root), env: { ...process.env, NODE_PATH: '' }, encoding: 'utf8', windowsHide: true, timeout: 180000 }); return { exit_code: child.status, stdout: child.stdout || '', stderr: child.stderr || '', spawn_error: child.error ? { code: child.error.code || null, message: child.error.message } : null }; }
function main() { const root = path.resolve(__dirname, '..'); const manifest = verifyManifest(root); phase = 'verifiers'; const zip = candidate(root); const checks = [ ['contained_lock_usage', 'verify-contained-lock-usage.js', []], ['contained_lock_physical', 'verify-contained-lock-rc39.js', ['--zip', zip]], ['context_lock_safety', 'verify-context-lock-safety-rc40.js', ['--zip', zip, '--expect', 'pass']], ['evidence_report_contract', 'verify-evidence-report-contract.js', ['--root', root]] ]; const results = checks.map(([id, script, args]) => { const actual = invoke(script, args, root); return { id, expected: { exit_code: 0 }, actual, pass: actual.exit_code === 0 }; }); const report = { schema_version: 'knowledge-audit-replay.v1', candidate: path.basename(zip), manifest, verifiers_started: verifiersStarted, checks_total: results.length, passed: results.filter((item) => item.pass).length, failed: results.filter((item) => !item.pass).length, status: results.every((item) => item.pass) ? 'pass' : 'fail', results }; process.stdout.write(JSON.stringify(report, null, 2) + '\n'); if (report.failed) process.exitCode = 1; }
try { main(); } catch (error) { process.stdout.write(JSON.stringify({ schema_version: 'knowledge-audit-replay.v1', status: 'fail', phase, verifiers_started: verifiersStarted, error: { message: error.message, manifest_path: error.manifest_path || null, expected_sha256: error.expected_sha256 || null, actual_sha256: error.actual_sha256 || null } }, null, 2) + '\n'); process.stderr.write((error.stack || error.message) + '\n'); process.exitCode = 1; }
